---
version: '3.2'
services:
  api:
    image: ${APP_NAME}/dev:latest
    container_name: api
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}"
        target: "/opt/app"
    command: /opt/app/docker/dev/api-entrypoint.sh
    user: "app"
    group_add:
      - sysadmin
    env_file:
      - "${ENV_PATH}"
    network_mode: host
  front:
    image: ${APP_NAME}/dev:latest
    container_name: front
    volumes:
      - type: bind
        source: "${PROJECT_ROOT}"
        target: "/opt/app"
    command: /opt/app/docker/dev/front-entrypoint.sh
    user: "app"
    group_add:
      - sysadmin
    network_mode: host